import { createThemeContract } from '@vanilla-extract/css';

export const colorTokens = createThemeContract({
  amber200: null,
  backgroundDark: null,
  backgroundLight: null,
  bgColor: null,
  black: null,
  borderColor: null,
  borderColorHover: null,
  error: null,
  errorHover: null,
  info: null,
  infoHover: null,
  primary: null,
  primaryHover: null,
  purple: null,
  purpleHover: null,
  slate100: null,
  slate200: null,
  slate300: null,
  slate400: null,
  slate500: null,
  slate600: null,
  slate700: null,
  slate800: null,
  slate900: null,
  success: null,
  successHover: null,
  textColor: null,
  warning: null,
  warningHover: null,
  white: null,
});
