catalog:
  '@base-ui-components/react': 1.0.0-beta.4
  '@biomejs/biome': 2.2.6
  '@hono/node-server': 1.19.5
  '@hono/vite-dev-server': 0.23.0
  '@iconify-json/fa7-brands': 1.2.0
  '@iconify-json/fa7-regular': 1.2.1
  '@iconify-json/fa7-solid': 1.2.2
  '@iconify/tools': 4.1.4
  '@iconify/types': 2.0.0
  '@react-router/dev': 7.9.2
  '@react-router/node': 7.9.4
  '@react-router/serve': 7.9.4
  '@types/node': 24.8.0
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.2
  '@unocss/preset-icons': 66.5.4
  '@unocss/preset-wind4': 66.5.4
  '@unocss/vite': 66.5.4
  hono: 4.9.12
  isbot: 5.1.31
  react: 19.2.0
  react-dom: 19.2.0
  react-router: 7.9.4
  typescript: 5.9.3
  unocss: 66.5.4
  vite: 7.1.10
  vite-tsconfig-paths: 5.1.4

catalogMode: strict

color: always

engineStrict: true

saveExact: true

savePrefix: ''

shellEmulator: true

verifyDepsBeforeRun: install
