name = "healthz-rust"
main = "build/index.js"
compatibility_date = "2026-05-13"
workers_dev = true
preview_urls = true
upload_source_maps = true

[cache]
enabled = true

[placement]
mode = "smart"

[observability]
enabled = true
head_sampling_rate = 1.0

[observability.logs]
enabled = true
head_sampling_rate = 1.0
invocation_logs = true
persist = true

[observability.traces]
enabled = true
head_sampling_rate = 1.0
persist = true

[env.canary]
name = "healthz-rust-canary"

[env.canary.vars]
SENTRY_DSN = "https://8dcd1f24afff2f432f13332d6e2837a1@o237444.ingest.us.sentry.io/4511078663782400"

[env.dev]
name = "healthz-rust-dev"

[env.dev.vars]
SENTRY_DSN = "https://8dcd1f24afff2f432f13332d6e2837a1@o237444.ingest.us.sentry.io/4511078663782400"

[env.production]
name = "healthz-rust-production"

[env.production.vars]
SENTRY_DSN = "https://8dcd1f24afff2f432f13332d6e2837a1@o237444.ingest.us.sentry.io/4511078663782400"
