export const criticalBaseCss = [
  'html {',
  '  box-sizing: border-box;',
  '  font-size: 16px;',
  '  font-weight: 400;',
  '  line-height: 1.5;',
  '  margin: 0;',
  '  padding: 0;',
  '  text-rendering: optimizeLegibility;',
  '}',
  '',
  '*,',
  '*::before,',
  '*::after {',
  '  box-sizing: inherit;',
  '}',
  '',
  'body {',
  '  margin: 0;',
  '}',
].join('\n');
