name: Deploy Canary

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
  DEPLOYMENT_BUILD: 'true'
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  SENTRY_DSN: ${{ vars.SENTRY_DSN }}
  SENTRY_RELEASE: ${{ github.sha }}
  VITE_SENTRY_DSN: ${{ vars.VITE_SENTRY_DSN }}
  VITE_POSTHOG_TOKEN: ${{ secrets.VITE_POSTHOG_TOKEN_CANARY }}
  VITE_POSTHOG_API_HOST: ${{ vars.VITE_POSTHOG_API_HOST }}

jobs:
  frontend_canary:
    name: Frontend Canary
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up Deno environment
        uses: ./.github/actions/setup-deno
      - name: Deploy Frontend Canary
        uses: ./.github/actions/deploy-frontend-canary

  bff_canary:
    name: BFF Canary
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up Deno environment
        uses: ./.github/actions/setup-deno
      - name: Deploy BFF Canary
        uses: ./.github/actions/deploy-bff-canary

  gateway_canary:
    name: Gateway Canary
    needs: healthz_rust_canary
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up Deno environment
        uses: ./.github/actions/setup-deno
      - name: Deploy Gateway Canary
        uses: ./.github/actions/deploy-gateway-canary

  healthz_rust_canary:
    name: Healthz Rust Canary
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up Deno environment
        uses: ./.github/actions/setup-deno
      - name: Deploy Healthz Rust Canary
        uses: ./.github/actions/deploy-healthz-rust-canary
